name: Build for Debian 12

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: sudo apt-get update && sudo apt-get install -y musl-tools pkg-config libssl-dev

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Compilar para Debian 12
        run: cargo build --release

      - name: Fazer upload do binário
        uses: actions/upload-artifact@v4
        with:
          name: export-wp-debian12
          path: target/release/export-wp

